<#assign tables=api.tables/>
<#assign views=api.views/>
/**
 * =============================
 * Generated by SQLiteGenerator
 * Copyright (C) 2016 UsherBaby
 * =============================
 */

package ${api.javaPackage};

import android.content.Context;
import android.database.DatabaseErrorHandler;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

final class ${api.dbOpenHelperClassName} extends SQLiteOpenHelper {

    public ${api.dbOpenHelperClassName}(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    public ${api.dbOpenHelperClassName}(Context context, String name, SQLiteDatabase.CursorFactory factory, int version, DatabaseErrorHandler errorHandler) {
        super(context, name, factory, version, errorHandler);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.beginTransaction();
        <#list tables?keys as key>
        db.execSQL("${stringHelper.toIFExists(tables[key])}");
        </#list>

        <#list views?keys as key>
        db.execSQL("${stringHelper.toIFExists(views[key])}");
        </#list>
        db.setTransactionSuccessful();
        db.endTransaction();
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        if (oldVersion < newVersion) {
            db.beginTransaction();
            <#list tables?keys as key>
            db.execSQL("DROP TABLE IF EXISTS ${key}");
            </#list>

            <#list views?keys as key>
            db.execSQL("DROP VIEW IF EXISTS ${key}");
            </#list>
            db.setTransactionSuccessful();
            db.endTransaction();

            onCreate(db);
        }
    }
}
