<#assign types=model.types/>
<#assign members=model.members/>
/**
 * =============================
 * Generated by SQLiteGenerator
 * Copyright (C) 2016 UsherBaby
 * =============================
 *
 * Code for table : ${model.tableName}
 * Columns: (<#list members?keys as key>${model.getColumnName(key)}<#if key_has_next> ,<#else>)</#if></#list>
 */

package ${model.javaPackage};

import android.database.Cursor;
import android.util.Log;
<#list types as t>
import ${t};
</#list>

public class ${model.className} extends ${model.superModelClassName} {

   <#list members?keys as key>
   <#if members[key]?has_content>
    private ${members[key]+' '+key};
   </#if>
   </#list>

    public ${model.className}() {
        tableName = "${model.tableName}";
    }

   <#list members?keys as key>
   <#if members[key]?has_content>
    public ${members[key]} get${stringHelper.camel2Pascal(key)}() {
        return ${"this."+key};
    }

    public void set${stringHelper.camel2Pascal(key)}(${members[key]+' '+key}) {
        ${"this."+key} = ${key};
    }

   </#if>
   </#list>
    @Override
    public Object[] getUpdateSql() {
        Object[] objects = new Object[${members?size + 1}];
        objects[0] = "${model.getUpdateSql()}";
        <#list members?keys as key>
        <#if key!='id'>
        objects[${model.getIndex()}] = this.${key + model.addIndex()};
        </#if>
        </#list>
        objects[${model.getIndex()}] = this.id${model.initIndex()};
        return objects;
    }

    @Override
    public Object[] getInsertSql() {
        Object[] objects = new Object[${members?size + 1 - model.getAutoIncrementMemberSize()}];
        objects[0] = "${model.getInsertSql()}";
        <#list members?keys as key>
        <#if model.isAutoIncrementMember(key)==false>
        objects[${model.getIndex()}] = this.${key + model.addIndex()};
        </#if>
        </#list>
        return objects;
    }

    @Override
    public Object[] getDeleteSql() {
        Object[] objects = new Object[2];
        objects[0] = "delete from ${model.tableName} where id=?";
        objects[1] = this.id;
        return objects;
    }

    @Override
    public void initValues(Cursor cursor) {
        try {
            <#if model.hasDateType>
            SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            </#if>
            <#list members?keys as key>
            if (cursor.getColumnIndex("${model.getColumnName(key)}") >= 0) {
            <#if members[key]=="boolean" || members[key]=="Boolean">
                this.${key} = Boolean.valueOf(cursor.${model.getCursorMethod(members[key])}(cursor.getColumnIndex("${model.getColumnName(key)}")));
            <#elseif members[key]=="Date">
                this.${key} = ft.parse(cursor.${model.getCursorMethod(members[key])}(cursor.getColumnIndex("${model.getColumnName(key)}")));
            <#else>
                this.${key} = cursor.${model.getCursorMethod(members[key])}(cursor.getColumnIndex("${model.getColumnName(key)}"));
            </#if>
            }
            </#list>
        } catch (Exception e) {
            Log.e("${model.className + ".initValue()"}", e.toString());
        }
    }
}