/**
 * =============================
 * Generated by SQLiteGenerator
 * Copyright (C) 2016 UsherBaby
 * =============================
 */

package com.example.ipad.unix.db;

import android.content.Context;
import android.content.ContextWrapper;
import android.database.DatabaseErrorHandler;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.os.Environment;
import android.support.annotation.NonNull;
import android.util.Log;

import java.io.File;
import java.io.IOException;

public final class DbContext extends ContextWrapper {
    protected String sdCardPath;

    public DbContext(Context context, @NonNull String sdCardPath) {
        super(context);
        this.sdCardPath = sdCardPath;
    }

    @Override
    public File getDatabasePath(String name) {
        if (!isSDCardEnable()) {
            Log.e("DbContext", "sdCard doesn't exit !");
            return null;
        } else {
            boolean isFileCreateSuccess = false;
            File dbFile = new File(sdCardPath);
            if (!dbFile.exists()) {
                try {
                    isFileCreateSuccess = dbFile.createNewFile();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                isFileCreateSuccess = true;
            }
            if (isFileCreateSuccess) return dbFile;
            return super.getDatabasePath(name);
        }
    }

    /**
     * override this method for opening database file in SdCard，android 2.3 =/- will call this method
     *
     * @param name
     * @param mode
     * @param factory
     */
    @Override
    public SQLiteDatabase openOrCreateDatabase(String name, int mode, CursorFactory factory) {
        return SQLiteDatabase.openOrCreateDatabase(getDatabasePath(name), null);
    }

    /**
     * Android 4.0 =/+ will call this method
     *
     * @param name
     * @param mode
     * @param factory
     * @param errorHandler
     * @see ContextWrapper#openOrCreateDatabase(String,
     * int,
     * CursorFactory,
     * DatabaseErrorHandler)
     */
    @Override
    public SQLiteDatabase openOrCreateDatabase(String name, int mode, CursorFactory factory, DatabaseErrorHandler errorHandler) {
        return SQLiteDatabase.openOrCreateDatabase(getDatabasePath(name), null);
    }

    private boolean isSDCardEnable() {
        return Environment.getExternalStorageState().equals(Environment.MEDIA_MOUNTED);
    }
}