/**
 * =============================
 * Generated by SQLiteGenerator
 * Copyright (C) 2016 UsherBaby
 * =============================
 */

package com.example.ipad.unix.db;

import android.content.Context;
import android.database.DatabaseErrorHandler;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

final class DBOpenHelper extends SQLiteOpenHelper {

    public DBOpenHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    public DBOpenHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version, DatabaseErrorHandler errorHandler) {
        super(context, name, factory, version, errorHandler);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.beginTransaction();
        db.execSQL("CREATE TABLE IF NOT EXISTS department (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS employee (id INTEGER PRIMARY KEY, name TEXT NOT NULL, departmentId INTEGER)");

        db.execSQL("CREATE VIEW IF NOT EXISTS employeeDepartment AS select t1.name,t2.name as 'department' from employee t1 join department t2 where t1.departmentId=t2.id");
        db.setTransactionSuccessful();
        db.endTransaction();
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        if (oldVersion < newVersion) {
            db.beginTransaction();
            db.execSQL("DROP TABLE IF EXISTS department");
            db.execSQL("DROP TABLE IF EXISTS employee");

            db.execSQL("DROP VIEW IF EXISTS employeeDepartment");
            db.setTransactionSuccessful();
            db.endTransaction();

            onCreate(db);
        }
    }
}
