/**
 * =============================
 * Generated by SQLite Generator
 * Copyright (C) 2016 UsherBaby
 * =============================
 *
 * Code for data view : employeeDepartment
 * Columns: (name ,department)
 */

package com.example.ipad.unix.model;

import android.database.Cursor;
import android.util.Log;

public class EmployeeDepartment extends SuperModel {

    private String name;
    private String department;

    public EmployeeDepartment() {
        tableName = "employeeDepartment";
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @Override
    public Object[] getUpdateSql() {
        throw new RuntimeException("Data View not support Update operation");
    }

    @Override
    public Object[] getInsertSql() {
        throw new RuntimeException("Data View not support Insert operation");
    }

    @Override
    public Object[] getDeleteSql() {
        throw new RuntimeException("Data View not support Delete operation");
    }

    @Override
    public void initValues(Cursor cursor) {
        try {
            if (cursor.getColumnIndex("name") >= 0) {
                this.name = cursor.getString(cursor.getColumnIndex("name"));
            }
            if (cursor.getColumnIndex("department") >= 0) {
                this.department = cursor.getString(cursor.getColumnIndex("department"));
            }
        } catch (Exception e) {
            Log.e("initValue()", e.toString());
        }
    }
}