/**
 * =============================
 * Generated by SQLiteGenerator
 * Copyright (C) 2016 UsherBaby
 * =============================
 */

package com.example.ipad.unix.model;

import android.database.Cursor;

public abstract class SuperModel {

    protected String tableName;

    public String getTableName() {
        return tableName;
    }

    public abstract Object[] getUpdateSql();

    public abstract Object[] getInsertSql();

    public abstract Object[] getDeleteSql();

    public abstract void initValues(Cursor cursor);
}