/**
 * =============================
 * Generated by SQLiteGenerator
 * Copyright (C) 2016 UsherBaby
 * =============================
 *
 * Code for table : department
 * Columns: (name ,id)
 */

package com.example.ipad.unix.model;

import android.database.Cursor;
import android.util.Log;

public class Department extends SuperModel {

    private String name;
    private int id;

    public Department() {
        tableName = "department";
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Override
    public Object[] getUpdateSql() {
        Object[] objects = new Object[3];
        objects[0] = "update department set name=? where id=?;";
        objects[1] = this.name;
        objects[2] = this.id;
        return objects;
    }

    @Override
    public Object[] getInsertSql() {
        Object[] objects = new Object[2];
        objects[0] = "insert into department (name) values (?);";
        objects[1] = this.name;
        return objects;
    }

    @Override
    public Object[] getDeleteSql() {
        Object[] objects = new Object[2];
        objects[0] = "delete from department where id=?";
        objects[1] = this.id;
        return objects;
    }

    @Override
    public void initValues(Cursor cursor) {
        try {
            if (cursor.getColumnIndex("name") >= 0) {
                this.name = cursor.getString(cursor.getColumnIndex("name"));
            }
            if (cursor.getColumnIndex("id") >= 0) {
                this.id = cursor.getInt(cursor.getColumnIndex("id"));
            }
        } catch (Exception e) {
            Log.e("Department.initValue()", e.toString());
        }
    }
}