<#assign types=model.types/>
<#assign members=model.members/>
/**
 * =============================
 * Generated by SQLite Generator
 * Copyright (C) 2016 UsherBaby
 * =============================
 *
 * Code for data view : ${model.tableName}
 * Columns: (<#list members?keys as key>${model.getColumnName(key)}<#if key_has_next> ,<#else>)</#if></#list>
 */

package ${model.javaPackage};

import android.database.Cursor;
import android.util.Log;
<#list types as t>
import ${t};
</#list>

public class ${model.className} extends ${model.superModelClassName} {

   <#list members?keys as key>
   <#if members[key]?has_content>
    private ${members[key]+' '+key};
   </#if>
   </#list>

    public ${model.className}() {
        tableName = "${model.tableName}";
    }

   <#list members?keys as key>
   <#if members[key]?has_content>
    public ${members[key]} get${stringHelper.camel2Pascal(key)}() {
        return ${"this."+key};
    }

    public void set${stringHelper.camel2Pascal(key)}(${members[key]+' '+key}) {
        ${"this."+key} = ${key};
    }

   </#if>
   </#list>
    @Override
    public Object[] getUpdateSql() {
        throw new RuntimeException("Data View not support Update operation");
    }

    @Override
    public Object[] getInsertSql() {
        throw new RuntimeException("Data View not support Insert operation");
    }

    @Override
    public Object[] getDeleteSql() {
        throw new RuntimeException("Data View not support Delete operation");
    }

    @Override
    public void initValues(Cursor cursor) {
        try {
            <#if model.hasDateType>
            SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            </#if>
            <#list members?keys as key>
            if (cursor.getColumnIndex("${model.getColumnName(key)}") >= 0) {
            <#if members[key]=="boolean" || members[key]=="Boolean">
                this.${key} = Boolean.valueOf(cursor.${model.getCursorMethod(members[key])}(cursor.getColumnIndex("${model.getColumnName(key)}")));
            <#elseif members[key]=="Date">
                this.${key} = ft.parse(cursor.${model.getCursorMethod(members[key])}(cursor.getColumnIndex("${model.getColumnName(key)}")));
            <#else>
                this.${key} = cursor.${model.getCursorMethod(members[key])}(cursor.getColumnIndex("${model.getColumnName(key)}"));
            </#if>
            }
            </#list>
        } catch (Exception e) {
            Log.e("initValue()", e.toString());
        }
    }
}